name: CI tests

on:
  - pull_request

jobs:
  check-stdout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Test with no options
        run: |
          ./calculator.py 2>&1 | cut -d: -f4- > test1.txt
          diff test1.txt tests/expected-result1.txt

      - name: Test debug
        run: |
          ./calculator.py --debug 2>&1 | cut -d: -f4- > test2.txt
          diff test2.txt tests/expected-result2.txt
